[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
genius_vault = "FnpUgSxeMQJAGYADfem4Zz7gf9i2sPJjYiK9ay8VBoJm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
